### ISSUE TITLE
Possible unsoundness with FPA

### ISSUE THREAD

**Issue by kanigsson** [OCamlPro/alt-ergo#1111]
[repr.ae.txt](https://github.com/OCamlPro/alt-ergo/files/15269432/repr.ae.txt)

On the attached file, I get this result:
```
$ alt-ergo repr.ae --enable-theories fpa
File "repr.ae", line 36, characters 3-111: Valid (0.0121) (107 steps) (goal defqtvc)
```
But I don't see any reason for the file to be valid.

This was originally reproduced with alt-ergo 2.4.0 and the options `--use-fpa --prelude fpa-theory-2019-10-08-19h00.ae`.

**Comment by bclement-ocp** [comment]
Thank you for the report ; this was indeed an unsoundness in the FPA module. It should be fixed by #1113; the fix has been merged into the `next` branch and will be part of the next release.

**Comment by kanigsson** [comment]
Thanks a lot for the quick fix! We probably can't apply the fix right away - Is removing the `float_of_pos_pow_of_two` axiom a sufficient workaround for this or do you have a better idea?

**Comment by bclement-ocp** [comment]
> Is removing the float_of_pos_pow_of_two axiom a sufficient workaround for this

I cannot say for sure. `float_of_pos_pow_of_two` is the axiom that triggered the bug in the repro, but since I had a code fix I did not check if other axioms in the prelude could trigger the same bug. If you go that route I'd modify the `find_particular_subst` function to print some logging information when it triggers, and remove axioms until `alt-ergo --use-fpa fpa-theory-2019-10-08-19h00.ae` no longer prints anything.

> do you have a better idea

Maybe the following patch can be helpful. It should have the same effect as the fix that went into `next` (however the patch that went into `next` removes bogus intermediate states and thus should be more robust in the long-term).

```patch
diff --git a/src/lib/structures/expr.ml b/src/lib/structures/expr.ml
index c05882c2..c0f0e1a9 100644
--- a/src/lib/structures/expr.ml
+++ b/src/lib/structures/expr.ml
@@ -1241,7 +1241,7 @@ and mk_forall_bis (q : quantified) id =
   if SMap.is_empty binders && Ty.Svty.is_empty q.main.vty then q.main
   else
     let q = {q with binders} in
-    match find_particular_subst binders q.user_trs q.main with
+    match find_particular_subst q.kind binders q.user_trs q.main with
     | None -> mk_forall_ter q 0
 
     | Some sbs ->
@@ -1281,8 +1281,10 @@ and find_particular_subst =
 
       | _ -> ()
   in
-  fun binders trs f ->
-    if not (Ty.Svty.is_empty f.vty) || has_hypotheses trs ||
+  fun decl_kind binders trs f ->
+    (* https://github.com/OCamlPro/alt-ergo/issues/1111 *)
+    let in_theory = decl_kind == Dtheory in
+    if in_theory || not (Ty.Svty.is_empty f.vty) || has_hypotheses trs ||
        has_semantic_triggers trs
     then
       None
```

**Comment by kanigsson** [comment]
Thanks for your answer. In your opinion, does removing `--use-fpa` and the prelude file avoid the bug?

**Comment by kanigsson** [comment]
In fact, we would like to keep the prelude file and only remove `--use-fpa` (for Alt-Ergo 2.4.0). This should avoid the bug, as you said it is in the FPA mechanism?

For context, this is to work around the issue in a version of SPARK where we can't upgrade Alt-Ergo. We plan to upgrade Alt-Ergo in other versions of SPARK.

**Comment by bclement-ocp** [comment]
Apologies for the late reply — it has been a bit of a busy week.

The bug is in semantic triggers, which are used exclusively by the FPA preludes and hence I generally consider them part of "FPA reasoning". Technically, users can also define their own semantic triggers in theory extensions (`theory` blocks) but to my knowledge nobody does so. Simply removing `--use-fpa` while keeping the prelude will not completely avoid the bug. It will reduce the chances that it triggers, but without further investigation I cannot say whether it becomes impossible or merely unlikely.

Unfortunately we (OCamlPro) are not able to provide free support for older branches. However, we can discuss an arrangement for us to perform an impact analysis of the bug and suggest appropriate mitigations strategies in a timely manner. I am sending you an email to discuss this further.
