### ISSUE TITLE
Problem with Options in OCaml 4.02 and >

### ISSUE THREAD

**Issue by tofgarion** [OCamlPro/alt-ergo#22]
Hello,

When installing Alt-Ergo 1.30 and the satML plugin with opam, using the 4.02.3 or a more recent version of OCaml compiler, the following error occurs when using the plugin:

```
alt-ergo -sat-plugin satML-plugin.cmxs

[Dynlink] Loading the SAT-solver in plugin "satML-plugin.cmxs" failed!
>> Failure message: cannot find file ~/satML-plugin.cmxs in search path

[Dynlink] Trying to load the plugin from "~/.opam/4.03.0/lib/alt-ergo/plugins/satML-plugin.cmxs" failed too!
>> Failure message: implementation mismatch on Options
```

The error does not occur with OCaml 4.01.0.

Best,

Christophe

**Comment by OCamlPro-Iguernlala** [comment]
This is probably due to changes in recent versions of OCaml.

1) When I compile Alt-Ergo and satML-plugin from sources without doing `make clean` between the two compilations, `./alt-ergo.opt -sat-plugin satML-plugin.cmxs` works fine

2) If I compile Alt-Ergo, do `make clean` after making a backup of `alt-ergo.opt`, compile `satML-plugin`, and then try something like `./alt-ergo-backup.opt -sat-plugin satML-plugin.cmxs`, I get an error message similar to yours.


A workaround is to compile Alt-Ergo and the plugin from sources:

0) opam remove alt-ergo satML-plugin
1) get the sources of Alt-Ergo
2) ./configure, eventually with something like --prefix $HOME/opam/4.02.3
3) make alt-ergo.opt satML-plugin.cmxs
4) make install-opt install-satML

@lefessan

**Comment by tofgarion** [comment]
Hi Mohamed,

Thanks, recompiling Alt-Ergo and the plugins from sources after removing them works perfectly!

Best,

Christophe
