### ISSUE TITLE
Alt-ergo-free 2.0.0 does not compile on armhf and ppc64 (ocaml 4.05)

### ISSUE THREAD

**Issue by treinen** [OCamlPro/alt-ergo#230]
Hello,

compilation of the free version 2.0.0 with ocaml 4.05 gives assembler errors, see 

https://buildd.debian.org/status/fetch.php?pkg=alt-ergo&arch=armhf&ver=2.0.0-3&stamp=1550118623&raw=0

https://buildd.debian.org/status/fetch.php?pkg=alt-ergo&arch=ppc64&ver=2.0.0-3&stamp=1550119064&raw=0

-Ralf

**Comment by Gbury** [comment]
Judging by the errors, it seems to be a problem with the ocaml compiler.

Looking quickly at the OCaml changes, I found a bugfix in 4.06 for ARM that might be related to the first error (value too large for field of 2 bytes) : https://github.com/ocaml/ocaml/blob/trunk/Changes#L1771 . Could you try with ocaml 4.06 and see if this fixes the first error ?

I could not find any reference to the second error in the changelog, but I found the following error report on mantis which might be related : https://caml.inria.fr/mantis/view.php?id=7667 . As far as I can tell, the bug was closed around or after the 4.06 release, so it might be worth trying to compile alt-ergo with ocaml 4.06 subsequent versions to see whether the bug has been fixed.

**Comment by treinen** [comment]
Thanks for having looked this up. Unfortunately we do not have ocaml 4.06 yet in debian, and I won't go through the moves to install it by hand on some slow and remote machine.

**Comment by Gbury** [comment]
Fair enough, ^^
I guess this issue can be closed then ?

**Comment by treinen** [comment]
I don't know your procedures but I think it would be useful to keep track of that fact that this is known issue, even when it is not your fault. Something like a flag not-for-us or wont-fix ?

**Comment by Gbury** [comment]
Labelled as wontfix (also fixed the typo in the title, ^^).

**Comment by Gbury** [comment]
After some discussions, we thought that maybe on ARM architectures where the native build fails, you could simply install the bytecode version (which should run correctly since it appears the compiler (including the bytecode runtime) builds on your machines), instead of the native version ?

**Comment by treinen** [comment]
Hello,

On Fri, Feb 22, 2019 at 08:59:03AM -0800, Guillaume Bury wrote:
> After some discussions, we thought that maybe on ARM architectures where the native build fails, you could simply install the bytecode version (which should run correctly since it appears the compiler (including the bytecode runtime) builds on your machines), instead of the native version ?

yes this should work but this is for after the release of debian Buster.

Thanks -Ralf.
-- 
Ralf Treinen
Institut de Recherche en Informatique Fondamentale
Équipe Preuves, Programmes et Systèmes
Université Paris Diderot, Paris, France.
http://www.irif.fr/~treinen/
