### ISSUE TITLE
Is it possible to configure this project without the gui?

### ISSUE THREAD

**Issue by Earnestly** [OCamlPro/alt-ergo#231]
I'd like to build just `bin` and `lib` targets without the `gui` but unfortunately the current `configure.ml` seems to call `dune` in such a way that it will result in an error after `lablgtk` is not found.

As I don't intend to build the `gui` at all is there a way via `./configure` or `dune` to skip checking these particular dependencies?

**Comment by Gbury** [comment]
Short answer is yes: you can even silently ignore the configure failure, and call `make bin` (though I would not recommend it).

Long answer:
First, note that the configure script accepts as unnamed argument a package name (either alt-ergo-lib, alt-ergo-parsers, alt-ergo, or altgr-ergo). If no package name is given, the configure script assumes you want to build all 4.
The configure script currently does two distinct and independent tasks:
- it configures the destination directories for the installation (defaulting to the values provided by the current opam installation), by generating two files that are required for the build, namely `Makefile.config` and `lib/util/version.ml`
- after generating these files, it checks for the presence of dune, and calls dune to check that the dependencies for the selected packages are there. This call to dune can fail and not prevent the rest of the build to continue, since the needed files have already been generated at this point.

That explains why you can ignore this particular failure of the configure script and go on calling the makefile targets. In order to make this process less annoying, the configure could have an extra option to disable dependency checking.


Finally, one important point: the `bin` and `lib` makefile targets are intended for development of alt-ergo, and not release and/or installation. Since the split of alt-ergo-lib into its own separate ocamlfind lib and opam package, you should now build and install each opam package sequentially, as in:
```
./configure alt-ergo-lib
make alt-ergo-lib
make install-lib

./configure alt-ergo-parsers
make alt-ergo-parsers
make install-parsers

./configure alt-ergo
make alt-ergo
make install-bin
```
(the `install-*` names are primarily there because `make install-alt-ergo-lib` felt strange and too long to type)

This is because the binary of alt-ergo should be compiled against the installed library in order for potential plugins to be built against the same library.

**Comment by Earnestly** [comment]
Thanks for the explanation.  It's amusing to see you list several reasons advocating for not overloading the build system with developmental convenience but instead for keeping those aspects separate.

I did initially ignore the result of `./configure` but I'll likely switch to multiple calls of it instead.  The only difference is the `install` part comes afterwards as it's not possible to install the binary globally (or not without awkwardness) prior to the rest.  I'll likely have to figure out a way to adjust `PATH` or find out if the `Makefile`s support passing in the bin directly.

That old chestnut of making software which does one thing do two things strikes me down again.  Thanks for preemptively pointing out the various other pitfalls I hadn't considered or even thought to ask.

**Comment by Gbury** [comment]
Actually, dune is able to build the lib locally, and the binary against the local lib, such that when installing both, everything works, that's actually what the `make install` command does: build and install everything in one go. So dune is definitely capable of doing that. The problem is really figuring out how to specify the correct targets for dune to do that.

By the way, I guess using opam isn't an option in your case ?

**Comment by Earnestly** [comment]
Yeah that's right as I'm creating a personal package.  Even if it's not ultimately necessary, how can you tell `dune` where to find the local libraries?  E.g. `-I` for C (or `ocaml` iirc) compilers.

As this is a proper package, there are a few requirements such as being able to compile the software without a connection to the internet and installation being done to a staging directory (i.e. `DESTDIR`) while still being able to accomodate being moved to a different location in the filesystem.

In many cases it would also be built in a minimal chroot to avoid filesystem and environmental pollution but I'm not taking such an approach, expecting instead that build systems are competent enough to handle not polluting themselves unless told otherwise.

**Comment by Gbury** [comment]
I suppose you already use the configure script options to set the destdir (most notably the `--prefix` option) ?

I guess the most clean option in your case would be to have different packages: one package for alt-ergo-lib, one for alt-ergo-parser and one for alt-ergo, much like what is done in opam. If that's an option for you, it would considerably simplify things.

If you really need one single package, the question becomes: do you want/need users to be able to use the lib (and consequently write and use plugins for alt-ergo) ? If that's not necessary, then you could skip some parts and only build/install the binary.

**Comment by Gbury** [comment]
Also, one very important thing for packaging is that there's a better way to install files than the `make install-*` commands. When building one of the packages (with `make alt-ergo-lib' for instance), dune should generate a `<pkg>.install` file (for instance, `alt-ergo-lib.install`), which contains all the files that need to be copied when installing, sorted into categories (e.g. `lib`, `bin`, `share`, `doc`, etc..). You can then simply copy the files listed, which is probably better for you than a `make install-*` commands which could do all sorts of strange things.

For instance, the install file for the alt-ergo package looks like this:
```
lib: [
  "_build/install/default/lib/alt-ergo/META" {"META"}
  "_build/install/default/lib/alt-ergo/opam" {"opam"}
]
bin: [
  "_build/install/default/bin/alt-ergo" {"alt-ergo"}
]
share: [
  "_build/install/default/share/alt-ergo/plugins/AB-Why3-plugin.cma" {"plugins/AB-Why3-plugin.cma"}
  "_build/install/default/share/alt-ergo/plugins/AB-Why3-plugin.cmxs" {"plugins/AB-Why3-plugin.cmxs"}
  "_build/install/default/share/alt-ergo/plugins/fm-simplex-plugin.cma" {"plugins/fm-simplex-plugin.cma"}
  "_build/install/default/share/alt-ergo/plugins/fm-simplex-plugin.cmxs" {"plugins/fm-simplex-plugin.cmxs"}
]
doc: [
  "_build/install/default/doc/alt-ergo/CHANGES"
  "_build/install/default/doc/alt-ergo/odoc-pages/index.mld" {"odoc-pages/index.mld"}
]
```

**Comment by OriginLabs-Iguernlala** [comment]
I'll close this (inactive) issue. Fee free to re-open it if there's still something to discuss.
