### ISSUE TITLE
Assert failure when parsing a file in 2.3.0

### ISSUE THREAD

**Issue by vprevosto** [OCamlPro/alt-ergo#245]
The attached file, generated by Frama-C/WP, is accepted by Alt-Ergo 2.2.0, but leads to an assertion failure in 2.3.0:
```
Fatal error: exception File "lib/structures/expr.ml", line 2056, characters 15-21: Assertion failed
```

A quick search seems to indicate that the issue lies in the recursive definition of function `L_count` (lines 612-621). Recursive functions are a nasty thing, and I wouldn't mind if Alt-Ergo would refuse this definition, but I'd expect a better error message.

[mjrty_no_majority_ensures_result_no_cand_Alt-Ergo.txt](https://github.com/OCamlPro/alt-ergo/files/3306892/mjrty_no_majority_ensures_result_no_cand_Alt-Ergo.txt)

**Comment by OCamlPro-mattiasdrp** [comment]
Sorry for the delay, 

I'm working on your issue. I was able to reduce it to a minimal problem : 

```
logic match_bool : bool, 'a, 'a -> 'a

function L_count (x : int) : int =
    let x = (x - 1) : int in
    let x_1 = L_count(x) in
    match_bool(true, x_1, x_1)

goal mjrty_no_majority_ensures_result_no_cand:
  forall i1, i2 : int.
  (0 < i1) -> (0 < i2)
```
This will result in the assertion failure. It allowed me to realise that this assertion failure doesn't appear in Alt-Ergo 2.2.0 so I'll try to fix it as fast as possible.

**Comment by OCamlPro-mattiasdrp** [comment]
Working on fixing the problem still. Found out this behaviour:

With my minimal example, the term is created like this:
```
(let 'x_1~3' = L_count(('x~2' - 1)) in
(L_count('x~2') = match_bool(true,'x_1~3','x_1~3')))
```
And it raises the assertion failure because the term contains `L_count(x)` and `L_count(x-1)`.
Changing `let x = L_count(x-1)` for `let x = L_count(x)` will make the program run smoothy.

If I write the same kind of function but with two different parameters:

```
function L_count (x : int) : int =
    let x_1 = L_count(x - 1) in
    let x_2 = L_count(x + 1) in
    match_bool(true, x_1, x_2)
```
It is created as the following term:
```
(L_count('x~2') = match_bool(true,L_count(('x~2' - 1)),L_count(('x~2' + 1))))
```

And this doesn't create any bug.

So I tried inlining my minimal example:
```
function L_count (x : int) : int =
    match_bool(true, L_count(x - 1), L_count(x - 1))
```

And as I thought, no bug.

**Comment by OriginLabs-Iguernlala** [comment]
The `assert failure` is raised in function `term_definition` used in triggers inference:
```
  let term_definition s e =
    match e.f, e.xs with
    | (Sy.Lit Sy.L_eq | Sy.Form Sy.F_Iff), [a;b] ->
      if head_is_name s a then a
      else if head_is_name s b then b
      else assert false

    | Sy.Lit Sy.L_neg_pred, [a] when head_is_name s a ->
      a
    | _ -> (* in case of simplifications *)
      if head_is_name s e then e
      else
        let s = TSet.filter (head_is_name s) (max_pure_subterms e) in
        match TSet.elements s with
        | [u] -> u
        | _ -> assert false (* XXX HERE XXX *)
```

### The reason is the following:

1 - During typechecking, functions and predicate defintions (`f(x) = ...`, `p(x) = ...`) are lifted to generic axioms (`axiom f: forall x. f(x) = ...`, `axiom p: forall x. p(x) <-> ...`

2 - During triggers inference, function `term_definition` is used to retrieve defining terms (`f(x)` and `p(x)` in the inlined examples) to use them as triggers. We do this because we lost them in transformation of step 1.

3 - In the example triggering the bug, `L_count`'s declaration is recursive, but this case was not expected to happen in function `term_definition`. As a consequence, the set `s` contains two elements (`{ L_count('x~2'), L_count(('x~2' - 1))}`) instead of just the defining term.

### How to fix:

We should either patch `term_definition` or find another way to retrieve what I'm calling `defining terms` in the explanation above.
