### ISSUE TITLE
if-then-else in terms

### ISSUE THREAD

**Issue by kanigsson** [OCamlPro/alt-ergo#247]
Hello Alt-ergo team,

what is the current situation wrt to if-then-else inside terms? Is it supported in Alt-ergo 2.3 and later or not yet?

As you know, Why3 currently uses the "eliminate_if" transformation when exporting to alt-ergo, but this transformation can easily explode. Supporting if-then-else in terms would allow us to remove this transformation.

**Comment by OCamlPro-Coquera** [comment]
Hello and sorry for my late answer,

If-then-else or supported inside terms since Alt-Ergo 2.3 however this support is very naïve. For example we do not support basic ite elimination such as `if 4 > 0 then ...` or `if cond then if not cond then ..`
Some ongoing works try to simplify this kind of elimination by preprocesing with supports for theories, but this works are still in their early days.

We did not yet bench our Why3 test suits with or without "eliminate_if" so i can't guarantee if their is any benefits to remove the transformation from why3 driver. We will try to evaluate this issue and remove the elimination in the why3 driver if needed

**Comment by kanigsson** [comment]
I think this issue is resolved now with recent improvements in why3 and alt-ergo.

**Comment by OCamlPro-Coquera** [comment]
You're right this issue is resolved with the latest version of the Alt-ergo driver of why3 (https://gitlab.inria.fr/why3/why3/-/blob/master/drivers/alt_ergo.drv) and the removal of `eliminate_if`.
