### ISSUE TITLE
Better support for integer exponentiation

### ISSUE THREAD

**Issue by yannickmoy** [OCamlPro/alt-ergo#253]
Hi Alt-Ergo team!

A recurring issue with all SMT solvers that we use is that integer exponentiation is very weakly supported, in part because SMT-LIB2 does not define it in any theory. Thus, we're using the Why3 axiomatiztion to translate to SMT-LIB2 syntax or Why3 syntax, and Alt-Ergo like other provers cannot prove sy that 2^14 fits in the bounds of an integer. Here is a VC that reflects that case below. Is there any hope of having better support for exponentiation in Alt-Ergo? Thanks in advance for your answer.

[expo.why.txt](https://github.com/OCamlPro/alt-ergo/files/3701188/expo.why.txt)

**Comment by OCamlPro-Coquera** [comment]
Hi Yannick,

I've open a PR(#255) which add the operation symbol `**` for the exponentiation in the native language of Alt-Ergo. This operation was already defined in the FPA arithmetics as `pow_real_int` and `pow_real_real`. We decided to rename and generalized it.
Since the smt-lib does not define such operation it can only be used in native language for the time being.
 
With the addition of the symbol `**` you should be  able to prove the following example :
[expo_why.txt](https://github.com/OCamlPro/alt-ergo/files/3707587/expo_why.txt)

In the future we will add this operation symbol to the _why3_ driver.

**Comment by yannickmoy** [comment]
That's great @OCamlPro-Coquera ! 

I see that in your modified example you're using real and integer. Will the VC still be proved when both the operand and the exponent are integers? 

We are indeed interested in the integration of this capability in Why3, so that we can mimic the same in the drivers we use for Alt-Ergo in SPARK.

**Comment by OCamlPro-Coquera** [comment]
Hi Yannick,

Before, `pow_real_real` and `pow_real_int` could only compute constants such as `pow_real_int(2.,14)` and this was used internally for Floating Point Arithmetic with the use of a prelude.

Now, we compute exponentiation constants modulo equality. Since my last message we decide to add two symbols : 
-  `**` for integer exponentiation with the type `Int -> Int -> Int`. Only positive exponent are allowed on integer exponentiation.
- `**.` for real exponentiation with the type `Int | Real -> Int | Real -> Real` replacing `pow_real_real` and `pow_real_int`. We do not support non integer exponent such as `3. **. 1.5`. 

Your VC will be proved if both the operand and the exponent are integers but you need to choose between `**` for integer result or `**.` for real one depending on your needs. 

In the future we will extend this work to support intervals for expressions such as `x **. y` or `x **. y` from intervals of `x` and `y`.

**Comment by OriginLabs-Iguernlala** [comment]
By `Only positive exponent are allowed on integer exponentiation.` and `We do not support non integer exponent`, Albin meant that the expressions remain `non-interpreted` otherwise (Alt-Ergo will not crash :-) )

**Comment by yannickmoy** [comment]
great news, thanks Albin, we'll try! Let us know if you update the Why3 driver to use the new exponent operator for integers, otherwise we'll do it ourselves.

**Comment by OriginLabs-Iguernlala** [comment]
Note that you should now use `fpa-theory-2019-10-08-19h00.why` prelude for FPA

As we are not currently maintaining the Why3 drivers. I'd say it's better to update yours to map `power` functions to `**` or `**.`

**Comment by yannickmoy** [comment]
thx Mohamed, we'll do that.

**Comment by kanigsson** [comment]
Hello Mohamed, 

You never seem to update the file `sources/prelude/dune`, so I get bitten every time I try to change the prelude file because it is not installed :-) Is that intended or simply an omission?

**Comment by OriginLabs-Iguernlala** [comment]
Indeed @kanigsson 

@OCamlPro-Coquera @Gbury this needs a small fix

**Comment by OCamlPro-Coquera** [comment]
Sorry for the omission. #259 should fix the issue.

**Comment by kanigsson** [comment]
Thank you
