### ISSUE TITLE
Unsupported algebraic data types

### ISSUE THREAD

**Issue by xldenis** [OCamlPro/alt-ergo#486]
Alt-Ergo raises an error when given the following type (through why3):

```
internal failure:  This declaration isn't supported:
                     type omg 'a =
                       | Omg
                   alt-ergo: algebraic datatype are not supported
```

**Comment by Stevendeo** [comment]
Alt-Ergo indeed raises an error when there is a single unused type variable. 

`type 'a omg = Omg` 

One can argue this type definition is valid or not for Alt-Ergo, however I am worried that

`type ('a, 'b) omg = Omg of {x : 'a}`

passes the typechecking.

In any case, the error message "alt-ergo: algebraic datatype are not supported" is clearly incorrect ; which version of Alt-Ergo do you use? Alt-Ergo definitely supports algebraic datatypes. Also, do you have a minimal example ?

**Comment by xldenis** [comment]
Alt-Ergo works with other algebraic types, I'm using version 2.4.0 installed from opan recently. I'll have to ask how I can extract the example from why3, but this why3 example will generate the error:

```
type omg 'a = Omg

let x (y : omg 'a) : () = assert { false }
```

In my personal opinion, this type is a perfectly valid algebraic type, and for alt-ergo after passing type checking should be indistinguishable in proofs from a unit type (from my naive point of view). 

Relevant Why3 issue: https://gitlab.inria.fr/why3/why3/-/issues/592

**Comment by hra687261** [comment]
The error message "alt-ergo: algebraic datatype are not supported" does not come from Alt-Ergo but from Why3 (here: https://gitlab.inria.fr/why3/why3/-/blob/3b160cd6a0d59e1f3b1125d7d4954342369467d2/src/printer/alt_ergo.ml#L378).

But ```omg``` still doesn't pass the type checking in Alt-Ergo:
```
type 'a omg = Omg
logic a: bool omg3
goal g:
    match a with
    | Omg -> true
    end
```
with the error: 
```
[Error]File "try-alt-ergo-file", line 1, characters 1-18:
Typing Error: Wrong number of arguments when applying omg
```

while ```omg2``` passes the type checking even thought there is an unused type parameter here as well:
```
type ('a, 'b) omg2 = Omg2 of {x2 : 'a}
logic a2:(bool, bool) omg2
goal g2: 
    match a2 with
    | Omg2 (_) -> true 
    end
```

So I think it is in fact a bug that should be fixed, but the error message in Why3 is also incorrect and should be corrected as well since Alt-Ergo does support algebraic data types, including in version 2.4.0 which is the version that is used in Why3 if I'm not mistaken.

**Comment by Stevendeo** [comment]
The issue #517 adresses the new issue, closing it.
