### ISSUE TITLE
[Build] Compilation error in src/plugins/AB-Why3/why3_parser.ml

### ISSUE THREAD

**Issue by thierry-FreeBSD** [OCamlPro/alt-ergo#501]
Trying to compile alt-ergo 2.4.1 on FreeBSD, with OCaml 4.12.1, menhir 20220210 and dune 2.8.0 gives the following error:

```
      menhir src/plugins/AB-Why3/why3_parser.{ml,mli} (exit 1)
(cd _build/default && /usr/local/bin/menhir --fixed-exception src/plugins/AB-Why3/why3_parser.mly --base src/plugins/AB-Why3/why3_parser)
Error: the code back-end requires the type of every nonterminal symbol to be
known. Please specify the type of every symbol via %type declarations, or
enable type inference (look up --infer in the manual).
Type inference is automatically enabled when Menhir is used via Dune,
provided the dune-project file says (using menhir 2.0) or later.
The types of the following nonterminal symbols are unknown:
anon_binder
any_qualid
bar_list1(type_case)
binder_var
binder_vars
binder_vars_head
binder_vars_rest
boption(IMPORT)
case_record
case_type_record
cast
clone_subst
…
etc.
```

If I replace `infer    false` by `infer    true` in src/plugins/AB-Why3/dune, the error becomes:
```
File "src/plugins/AB-Why3/why3_parser.ml", line 1155, characters 62-64:
1155 |   | MenhirCell1_clone_subst of 's * ('s, 'r) _menhir_state * ('a option)
                                                                     ^^
Error: The type variable 'a is unbound in this type declaration.
```

**Comment by Gbury** [comment]
There was a recent PR that fixed that build issue (see #495 ), unfortunately there hasn't been a release since it was merged. However, a fix was merged into opam-repository to add an upper bound on the version of menhir for alt-ergo.2.4.1 (see ocaml/opam-repository#20303 ), which should prevent trying to install alt-ergo with versions of menhir that are too recent and break the build, at least when using opam.

To fix your problem, you have two options:
- install a version of menhir compatible with alt-ergo. With opam, this should happen automatically if you `opam update` to get a repo that is up-to-date; without opam, you'll probably need to do this manually, for the record the latest release of menhir compatible with alt-ergo.2.4.1 is menhir.20211215
- or if you want/need a more up-to-date version of menhir, you can try and install the dev version of alt-ergo (until the next release). With opam, it is as simple as `opam pin add --dev alt-ergo`.

**Comment by Gbury** [comment]
For reference, here are the current version constraints for alt-ergo.2.4.1 :

https://github.com/ocaml/opam-repository/blob/master/packages/alt-ergo/alt-ergo.2.4.1/opam#L13-L19

(note that cmdliner also has had recent changes that necessitated adding dependency bounds)

**Comment by thierry-FreeBSD** [comment]
Thanks for your quick answer!
Since I'm trying to make coherent the various OCaml ports of FreeBSD, I have chosen to apply the patch, and everything is fine now.
