### ISSUE TITLE
The non-regression tests don't run again after modifying the binary

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#638]
The commands `make runtest` or `dune runtest` don't always run again the non-regression tests after
some modifications of the binary. I have to clean the directory to get the expected behavior.

I guess the issue comes from my PR #559.

**Comment by bclement-ocp** [comment]
Given #559 I would guess you have to run `dune build @runtest-quick`.

I am not really sure why we need `runtest-quick`, if the issue is that `dune build` runs too many tests can we just do `dune build @src/bin/text/all` in `make bin`?

(I personally use `dune exec --release -- alt-ergo` which doesn't seem to build the tests)
