### ISSUE TITLE
Make sure that the documentation on the website is that of the last release

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#693]
Not of unreleased code ;)

**Comment by Halbaroth** [comment]
The current workflow is as follow:
There is a branch `gh-pages` and a GitHub action in `documentation.yml` that build and push the documentation from `next` to the branch `gh-pages` as soon as we push on `next`. 

The branch `main` is not up to date. We should push the branch 2.4.x on it and modify the GitHub action in order to use this branch as reference for the documentation.

**Comment by bclement-ocp** [comment]
(Taking over this one)
