### ISSUE TITLE
enhance smt2->why translation script or smt2 front-end for alt-ergo

### ISSUE THREAD

**Issue by florianschanda** [OCamlPro/alt-ergo#72]
Some unordered suggestions on how this could be improved:
- support declare-const (crashes tools)
- support/ignore set-option :produce-models (crashes tools)
- bitvector / float conversions (why3 errors about unbound symbols)
- error/return with exit code 1 if there is a translation error so errors in batch translations are easier to notice

However, even better would be an SMT-LIB front-end for Alt-Ergo.

**Comment by OCamlPro-Iguernlala** [comment]
Héhé, an SMT-LIB frontend for Alt-Ergo ...

We are currently considering this point.  But due to limited resources, the first iteration(s) will probably focus on needs and constructs encountered in deductive program verification: not incremental, not heavy use of ITEs that requires pre-processing, ...

For the translator SMT2-> Why3 , it is not maintained.

**Comment by OCamlPro-Iguernlala** [comment]
Planned (as said in https://github.com/OCamlPro/alt-ergo/issues/70)
