### ISSUE TITLE
Test the shostak cache

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#779]
The PR https://github.com/OCamlPro/alt-ergo/commit/fb6b7f27ff047d0236be1fd70b9c7f2add783fa7 fixes a cache in `Shostak.ml` that prevents to recreate semantic values. 

We don't know if this cache improves the performances. We should test it.

**Comment by bclement-ocp** [comment]
While investigating for #798 I realized that the Shostak cache should be mostly useless because most calls to `X.make` goes through the `Uf` module, and the `Uf` module maintains its own mapping from terms to semantic values, and only calls `X.make` on terms that are not in the mapping.

There are two possible conclusions from this:
 - Either we remove the Shostak cache,
 - Or we remove the mapping from terms to semantic values in `Uf` and just use the Shostak cache

Although the 2nd option might worsen things wrt term ordering (but probably not too much, because all terms are already in the hconsing table and AFAIK the semantic value's IDs are not semantically meaningful), it should be better for performance as it would use a hash table rather than a map, and would also avoid recomputing semantic values across SAT branches.

**Comment by bclement-ocp** [comment]
Note: if theories create fresh names in `make`, having a global cache is useful to make sure that the same names are created in all environments.

We used to do this for euclidean division but we no longer do ( #875 ).

**Comment by Halbaroth** [comment]
I agree. We can close this issue as the cache is useful for normalization and we didn't notice slow down.
