### ISSUE TITLE
Stack overflow

### ISSUE THREAD

**Issue by AllanBlanchard** [OCamlPro/alt-ergo#964]
The following file produces a stack overflow. Note that I don't know if it is provable or not, this is a reduced example.
[bug.txt](https://github.com/OCamlPro/alt-ergo/files/13435641/bug.txt)

**Comment by bclement-ocp** [comment]
Thanks for the report. I can confirm the issue on both the development branch and Alt-Ergo 2.5.2. It looks like we are trying to substitute a term with another term that contains it, which is not going to work. I will investigate.

**Comment by bclement-ocp** [comment]
Great: this is a case where there are two separate AC symbols, and it turns out that we don't do things properly. We were just talking with @Gbury the other day and noticed that what Alt-Ergo implements is not actually what is described in [the paper](https://arxiv.org/abs/1207.3262) that's suppose to describe it, and that we should investigate this as it could be problematic… so this proves that, I guess.

The issue is as follows:

 - The `bug.txt` introduces an AC symbol `gcd` to compute the greatest common divisor.
 - Alt-Ergo treats the built-in multiplication as an AC symbol (but this should work with any other AC symbol)
 - At some point we try to solve: `div(gcd(i1, 0), gcd(abs(i), i2))'*'i1 = gcd((-div(gcd(i1, 0), gcd(abs(i), i2))'*'i1),(0))` which is a term of the form `a * b = gcd(-(a * b), c)`
 - Because as symbols, `*` is an operator and `gcd` is a name, `Ac.compare` decides that the equation is properly oriented
 - Then we look while trying to apply the substitution `a * b → gcd(-(a * b), c)` to `gcd(-(a * b), c)`.

Minimal reproducer:

```alt-ergo
logic ac u : int, int -> int
logic ac v : int, int -> int

goal g : v(0, 1) = u(-v(0, 1), 2)
```

(Side note: `v(0, 1) = u(v(0, 1), 2)` actually works because Alt-Ergo performs a variant of the abstraction procedure described in the paper for nested AC symbols in `Ac.abstract2`)
